# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miti', models.DateTimeField(null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('specification', models.CharField(blank=True, max_length=600, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
