# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question1', '0002_openingstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='miti',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='quantity',
            field=models.PositiveIntegerField(default=34),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='remarks',
            field=models.TextField(blank=True, default='Sample remarks', null=True),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='specification',
            field=models.CharField(blank=True, default='Sample Spec', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='openingstock',
            name='value',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=100),
        ),
        migrations.AddField(
            model_name='openingstock',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question1.Item'),
        ),
    ]
